config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :questions
  resources :rounds, only: [:edit, :update]
  resources :games do
    member do
      patch "start"
      patch "next_round"
      patch "process_results"
      patch "show_results"
      get "join"
    end
  end
  resources :teams, only: [:show, :update]
  resources :team_answers, only: [:update]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :round
  has_one :team, through: :round

  has_many :team_answers, dependent: :destroy do
    def for_team(team)
      find_or_create_by(team: team)
    end
  end
end

# == Schema Information
#
# Table name: questions
#
#  id         :uuid             not null, primary key
#  answer     :text
#  number     :integer          not null
#  question   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  round_id   :uuid             not null
#
# Indexes
#
#  index_questions_on_round_id  (round_id)
#
# Foreign Keys
#
#  fk_rails_...  (round_id => rounds.id)
#

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= turbo_frame_tag dom_id(question)
  = form_with(model: question, class: 'box is-shadowless') do |form|
    == render 'components/form/form_errors', object: question

    h4.title.is-4 Question #{ question.number }

    .field.is-horizontal
      == render 'components/form/text_field', form: form, field: :question
      .field-label <!-- Left empty for spacing -->
      .field-body
    .field.is-horizontal
      = render 'components/form/text_field', form: form, field: :answer
      = render 'components/form/button', form: form

app/views/questions/_question.html.slim
p
  strong Question:
  = question.question

  strong Answer:
  = question.answer

= link_to 'Edit', edit_question_path(question)
= link_to 'Back', questions_path