config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :questions
  resources :rounds, only: [:edit, :update]
  resources :games do
    member do
      patch "start"
      patch "next_round"
      patch "process_results"
      patch "show_results"
      get "join"
    end
  end
  resources :teams, only: [:show, :update]
  resources :team_answers, only: [:update]
end

app/models/game.rb
class Game < ApplicationRecord
  include RelationshipUpdatable

  has_many :rounds, -> { order(:number) }, dependent: :destroy
  has_many :teams, -> { order(:number) }, dependent: :destroy

  has_one :first_round, -> { where(number: 1) }, class_name: "Round"
  has_one :current_round, ->(game) { where(number: game.current_round_number) }, class_name: "Round"
  has_one :next_round, ->(game) { where(number: game.current_round_number + 1) }, class_name: "Round"
  has_many :visible_rounds,
    -> { where(status: [statuses[:started], statuses[:finished], statuses[:scored]]).order(:number) },
    class_name: "Round"
  enum status: %i[pending_start started pending_results finished], _default: "pending_start"

  validates :number_of_rounds, presence: true
  validates :name, presence: true

  after_save :update_rounds_and_teams

  broadcasts

  def start!
    started!
    rounds.first.started!
    update!(current_round_number: 1)
    # make sure all answer objects are ready
    rounds.each do |round|
      round.questions.each do |question|
        teams.each do |team|
          question.team_answers.for_team(team)
        end
      end
    end
    broadcast_reload_teams
  end

  def next_round!
    started! unless started?
    current_round.finished! if current_round.present?
    next_round.started!
    update!(current_round_number: (current_round_number + 1))
    broadcast_reload_teams
  end

  def process_results!
    current_round.finished!
    pending_results! unless pending_results?
    broadcast_reload_teams
  end

  def show_results!
    finished! unless finished!
    teams.each(&:update_total_points!)
    broadcast_reload_teams
  end

  def reset!
    update(current_round_number: 0, status: :pending_start)
    rounds.update_all(status: :pending_start)
    teams.reload.each { |team| team.reload.broadcast_replace_to team }
  end

  def progress
    100 / number_of_rounds
  end

  def results
    teams.reorder(total_points: :desc).each_with_object({}) do |team, map|
      map[team.total_points].present? ? map[team.total_points] << team : map[team.total_points] = [team]
    end
  end

  private

  def broadcast_reload_teams
    teams.reload.each { |team| team.reload.broadcast_replace_to team }
  end

  def update_rounds_and_teams
    update_relationship_to_amount(rounds, number_of_rounds)
    update_relationship_to_amount(teams, number_of_teams)
  end
end

# == Schema Information
#
# Table name: games
#
#  id                   :uuid             not null, primary key
#  name                 :string
#  number_of_rounds     :integer          default(3)
#  number_of_teams      :integer          default(2)
#  current_round_number :integer          default(0)
#  status               :integer          default("pending_start")
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :destroy, :edit, :start, :next_round, :show_results, :process_results, :join]
  before_action :authenticate_user!, except: [:join]

  # GET /games
  def index
    @games = Game.all.order(created_at: :desc)
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  def edit
  end

  def join
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to edit_game_path(@game, step: 2), status: 303 }
        # format.turbo_stream { render turbo_stream: turbo_stream.replace("game_wizard", partial: "games/game_wizard", locals: {game: @game}) }
        # format.html { redirect_to @game, notice: "Game was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("game_wizard", partial: "games/form", locals: {game: @game}) }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /games/1
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("game_wizard", partial: "games/game_wizard", locals: {game: @game}) }
        format.html { redirect_to @game, notice: "Game was successfully updated." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@game, partial: "games/form", locals: {game: @game}) }
        format.html { render :edit }
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def start
    @game.start!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "game_wizard",
          partial: "games/game",
          locals: {game: @game, notice: "Game started"}
        )
      end
    end
  end

  def next_round
    @game.next_round!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "game_wizard",
          partial: "games/game",
          locals: {game: @game, notice: "Next round started"}
        )
      end
    end
  end

  def process_results
    @game.process_results!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "game_wizard",
          partial: "games/game",
          locals: {game: @game, notice: "Participants are now waiting for the results"}
        )
      end
    end
  end

  def show_results
    @game.show_results!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "game_wizard",
          partial: "games/game",
          locals: {game: @game, notice: "Game finished"}
        )
      end
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def round_param
    params.permit(:round_id)
  end

  def game_params
    params.require(:game).permit(:name, :number_of_rounds, :number_of_teams, :current_round_number)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def game_state_class(state)
    case state
    when 'pending_start'
      'is-info is-light'
    when 'started'
      'is-danger is-light'
    when 'pending_results'
      'is-warning is-light'
    when 'finished'
      'is-success is-light'
    end
  end
end

app/views/games/_finished.html.slim
.card-content
  .content
    h1.title = game.name
    == render 'components/form/notice', notice: notice
    == render 'games/results', game: game, team: nil

  footer.card-footer
    .card-footer-item
    .card-footer-item
    .card-footer-item

app/views/games/_form.html.slim
= form_with(model: game, data: { 'turbo-frame': '_top' }) do |form|
  == render 'components/form/form_errors', object: game
  .field.is-horizontal
    = render 'components/form/text_field', form: form, field: :name, width: '50%'
  .field.is-horizontal
    = render 'components/form/number_field', form: form, field: :number_of_rounds
  .field.is-horizontal
    = render 'components/form/number_field', form: form, field: :number_of_teams
  .field.is-horizontal
    = render 'components/form/button', form: form

app/views/games/_game.html.slim
= turbo_frame_tag dom_id(game)
  - if game.pending_start?
    == render 'games/pre_start', game: game, notice: notice
  - elsif game.started?
    == render 'games/started', game: game, notice: notice
  - elsif game.pending_results?
    == render 'games/pending_results', game: game, notice: notice
  - elsif game.finished?
    == render 'games/finished', game: game, notice: notice

app/views/games/_game_wizard.html.slim
= turbo_frame_tag 'game_wizard'
  .card-content
    .content
      h1.title = @game.name

      == render 'rounds/form', round: @game.first_round

  footer.card-footer
    = link_to 'Edit', edit_game_path(@game), class: "card-footer-item"
    .card-footer-item
    .card-footer-item

app/views/games/_pending_results.html.slim
.card-content
  h1.title = game.name
  == render 'components/form/notice', notice: notice
  == render 'games/round_tabs', game: game

  .content
    - game.teams.each do |team|
      == render 'games/team_answers', team: team, round: current_viewing_round(game)

  footer.card-footer
    .card-footer-item
    .card-footer-item
    .card-footer-item
      = form_with(model: game, url: show_results_game_path(game)) do |form|
        = form.submit t(:show_results), class: 'button is-primary is-inverted'

app/views/games/_pre_start.html.slim
.card-content
  .content
    h1.title = game.name
    == render 'components/form/notice', notice: notice
    table.table.is-striped.is-hoverable
      thead
        tr
          th Round number
          th Round name
          th Number of questions

      tbody
      - game.rounds.each do |round|
        tr
          td = round.number
          td = round.name
          td = round.questions.count

    .notification.is-warning = t(:team_notification)

    table.table.is-striped.is-hoverable
      thead
        tr
          th Team
          th Name
          th Link

      tbody
        - game.teams.each_with_index do |team|
          tr
            td = team.id
            td = team.display_name
            td = link_to(nil, team)

  footer.card-footer
    = link_to 'Edit', edit_game_path(game), class: "card-footer-item", data: { 'turbo-frame': '_top' }
    .card-footer-item
    .card-footer-item
      = form_with(model: game, url: start_game_path(game)) do |form|
        = form.submit 'Start the game!', class: 'button is-primary is-inverted'

app/views/games/_results.html.slim
div
  h4 Results for #{game.name}
  table.table.is-hoverable
    thead
      tr
        th Position
        th Team
        th Total points
        - game.rounds.each do |round|
          th = round.name.capitalize
    tbody
      - game.results.each_with_index do |(points, teams), index|
        - teams.each_with_index do |list_team, team_index|
          tr *{class: list_team.id == team&.id ? 'is-selected' : '' }
            td = team_index.zero? ? index + 1 : ''
            td = list_team.name
            td = points
            - game.rounds.each do |round|
              td = list_team.points_for_round(round)

app/views/games/_round_tabs.html.slim
.tabs.is-boxed
  ul
    - game.visible_rounds.each do |round|
      li *{ class: rounds_tab_class(game, round) }
        a *{ href: game_path(game, round_id: round.id) }
          - if round.scored?
            span.icon.is-small
              i.fas.fa-check-square aria-hidden="true"
          = round.name

app/views/games/_started.html.slim
.card-content
  h1.title  = game.name
  == render 'components/form/notice', notice: notice
  == render 'games/round_tabs', game: game

  .content
    - if game.rounds.finished.count > 0
      - game.teams.each do |team|
        == render 'games/team_answers', team: team, round: current_viewing_round(game)
    - else
      p Answers will appear here

  footer.card-footer
    .card-footer-item
    .card-footer-item
    .card-footer-item
      - if game.next_round.present?
        = form_with(model: game, url: next_round_game_path(game)) do |form|
          = form.submit t(:next_round), class: 'button is-primary is-inverted'
      - else
        = form_with(model: game, url: process_results_game_path(game)) do |form|
          = form.submit t(:process_results), class: 'button is-primary is-inverted'

app/views/games/_team_answers.html.slim
.block
  h3 = "#{team.name} (#{team.total_points})"
  table.table.is-striped.is-hoverable
    thead
      tr
        th Question
        th Correct Answer
        th Given Answer
        th Score

    tbody
      - team.answers_for_round(round).each do |answer|
        tr
          td Question #{ answer.question.number }
          td = answer.question.answer
          td = answer.answer
          td
            == render 'team_answers/form', answer: answer
      tr
        td Total points
        td
        td
        td
          = turbo_frame_tag "points_#{dom_id(round)}_#{dom_id(team)}"
            = team.answers_for_round(round).sum(:points)

app/views/games/edit.html.slim
.column
  .card
    - if params[:step] == "2"
      == render 'games/game_wizard', game: @game
    - else
      = turbo_frame_tag 'game_wizard' do
        .card-content
          .content
            h1.title = t(:new_game)
            == render 'form', game: @game

app/views/games/join.html.slim
.column
  .card
    .card-content
      .content
        h1.title = "Welcome to the game: #{@game.name}"
        == render 'components/form/notice', notice: notice
        = "Session: #{session.id}"
        = Redis.current.get "test"

app/views/games/new.html.slim
.column
  .card
    = turbo_frame_tag 'game_wizard'
      .card-content
        .content
          h1.title = t(:new_game)
          == render 'form', game: @game

app/views/games/show.html.slim
= turbo_stream_from @game
.column
  .card
    == render 'games/game', game: @game